# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.queue_manager_api import QueueManagerApi


class TestQueueManagerApi(unittest.TestCase):
    """QueueManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QueueManagerApi()

    def tearDown(self) -> None:
        pass

    def test_delete_queue(self) -> None:
        """Test case for delete_queue

        Delete Queue
        """
        pass

    def test_flush_queue(self) -> None:
        """Test case for flush_queue

        Flush Queue
        """
        pass

    def test_get_queue(self) -> None:
        """Test case for get_queue

        Get Queue
        """
        pass


if __name__ == '__main__':
    unittest.main()
