# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.aliases_api import AliasesApi


class TestAliasesApi(unittest.TestCase):
    """AliasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AliasesApi()

    def tearDown(self) -> None:
        pass

    def test_create_alias(self) -> None:
        """Test case for create_alias

        Create alias
        """
        pass

    def test_create_time_limited_alias(self) -> None:
        """Test case for create_time_limited_alias

        Create time limited alias
        """
        pass

    def test_delete_alias(self) -> None:
        """Test case for delete_alias

        Delete alias
        """
        pass

    def test_get_aliases(self) -> None:
        """Test case for get_aliases

        Get aliases
        """
        pass

    def test_get_time_limited_aliases(self) -> None:
        """Test case for get_time_limited_aliases

        Get time limited aliases
        """
        pass

    def test_update_alias(self) -> None:
        """Test case for update_alias

        Update alias
        """
        pass


if __name__ == '__main__':
    unittest.main()
