# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.mailboxes_api import MailboxesApi


class TestMailboxesApi(unittest.TestCase):
    """MailboxesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MailboxesApi()

    def tearDown(self) -> None:
        pass

    def test_create_mailbox(self) -> None:
        """Test case for create_mailbox

        Create mailbox
        """
        pass

    def test_delete_mailbox(self) -> None:
        """Test case for delete_mailbox

        Delete mailbox
        """
        pass

    def test_delete_mailbox_tags(self) -> None:
        """Test case for delete_mailbox_tags

        Delete mailbox tags
        """
        pass

    def test_edit_mailbox_spam_filter_score(self) -> None:
        """Test case for edit_mailbox_spam_filter_score

        Edit mailbox spam filter score
        """
        pass

    def test_get_mailbox_or_global_spam_filter_score(self) -> None:
        """Test case for get_mailbox_or_global_spam_filter_score

        Get mailbox or global spam filter score
        """
        pass

    def test_get_mailboxes(self) -> None:
        """Test case for get_mailboxes

        Get mailboxes
        """
        pass

    def test_get_mailboxes_of_a_domain(self) -> None:
        """Test case for get_mailboxes_of_a_domain

        Get mailboxes of a domain
        """
        pass

    def test_quarantine_notifications(self) -> None:
        """Test case for quarantine_notifications

        Quarantine Notifications
        """
        pass

    def test_update_mailbox(self) -> None:
        """Test case for update_mailbox

        Update mailbox
        """
        pass

    def test_update_mailbox_acl(self) -> None:
        """Test case for update_mailbox_acl

        Update mailbox ACL
        """
        pass

    def test_update_mailbox_custom_attributes(self) -> None:
        """Test case for update_mailbox_custom_attributes

        Update mailbox custom attributes
        """
        pass

    def test_update_pushover_settings(self) -> None:
        """Test case for update_pushover_settings

        Update Pushover settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
