# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.quarantine_api import QuarantineApi


class TestQuarantineApi(unittest.TestCase):
    """QuarantineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuarantineApi()

    def tearDown(self) -> None:
        pass

    def test_delete_mails_in_quarantine(self) -> None:
        """Test case for delete_mails_in_quarantine

        Delete mails in Quarantine
        """
        pass

    def test_get_mails_in_quarantine(self) -> None:
        """Test case for get_mails_in_quarantine

        Get mails in Quarantine
        """
        pass


if __name__ == '__main__':
    unittest.main()
