# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.models.update_mailbox_custom_attributes_request import UpdateMailboxCustomAttributesRequest

class TestUpdateMailboxCustomAttributesRequest(unittest.TestCase):
    """UpdateMailboxCustomAttributesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateMailboxCustomAttributesRequest:
        """Test UpdateMailboxCustomAttributesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateMailboxCustomAttributesRequest`
        """
        model = UpdateMailboxCustomAttributesRequest()
        if include_optional:
            return UpdateMailboxCustomAttributesRequest(
                attr = mailcow_sdk.models.update_mailbox_custom_attributes_request_attr.Update_mailbox_custom_attributes_request_attr(
                    attribute = mailcow_sdk.models.attribute.attribute(), 
                    value = mailcow_sdk.models.value.value(), ),
                items = None
            )
        else:
            return UpdateMailboxCustomAttributesRequest(
        )
        """

    def testUpdateMailboxCustomAttributesRequest(self):
        """Test UpdateMailboxCustomAttributesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
