# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.routing_api import RoutingApi


class TestRoutingApi(unittest.TestCase):
    """RoutingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutingApi()

    def tearDown(self) -> None:
        pass

    def test_create_sender_dependent_transports(self) -> None:
        """Test case for create_sender_dependent_transports

        Create Sender-Dependent Transports
        """
        pass

    def test_create_transport_maps(self) -> None:
        """Test case for create_transport_maps

        Create Transport Maps
        """
        pass

    def test_delete_sender_dependent_transports(self) -> None:
        """Test case for delete_sender_dependent_transports

        Delete Sender-Dependent Transports
        """
        pass

    def test_delete_transport_maps(self) -> None:
        """Test case for delete_transport_maps

        Delete Transport Maps
        """
        pass

    def test_get_sender_dependent_transports(self) -> None:
        """Test case for get_sender_dependent_transports

        Get Sender-Dependent Transports
        """
        pass

    def test_get_transport_maps(self) -> None:
        """Test case for get_transport_maps

        Get Transport Maps
        """
        pass


if __name__ == '__main__':
    unittest.main()
