# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.ratelimits_api import RatelimitsApi


class TestRatelimitsApi(unittest.TestCase):
    """RatelimitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RatelimitsApi()

    def tearDown(self) -> None:
        pass

    def test_edit_domain_ratelimits(self) -> None:
        """Test case for edit_domain_ratelimits

        Edit domain ratelimits
        """
        pass

    def test_edit_mailbox_ratelimits(self) -> None:
        """Test case for edit_mailbox_ratelimits

        Edit mailbox ratelimits
        """
        pass

    def test_get_domain_ratelimits(self) -> None:
        """Test case for get_domain_ratelimits

        Get domain ratelimits
        """
        pass

    def test_get_mailbox_ratelimits(self) -> None:
        """Test case for get_mailbox_ratelimits

        Get mailbox ratelimits
        """
        pass


if __name__ == '__main__':
    unittest.main()
