# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.address_rewriting_api import AddressRewritingApi


class TestAddressRewritingApi(unittest.TestCase):
    """AddressRewritingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AddressRewritingApi()

    def tearDown(self) -> None:
        pass

    def test_create_bcc_map(self) -> None:
        """Test case for create_bcc_map

        Create BCC Map
        """
        pass

    def test_create_recipient_map(self) -> None:
        """Test case for create_recipient_map

        Create Recipient Map
        """
        pass

    def test_delete_bcc_map(self) -> None:
        """Test case for delete_bcc_map

        Delete BCC Map
        """
        pass

    def test_delete_recipient_map(self) -> None:
        """Test case for delete_recipient_map

        Delete Recipient Map
        """
        pass

    def test_get_bcc_map(self) -> None:
        """Test case for get_bcc_map

        Get BCC Map
        """
        pass

    def test_get_recipient_map(self) -> None:
        """Test case for get_recipient_map

        Get Recipient Map
        """
        pass


if __name__ == '__main__':
    unittest.main()
