# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.fordwarding_hosts_api import FordwardingHostsApi


class TestFordwardingHostsApi(unittest.TestCase):
    """FordwardingHostsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FordwardingHostsApi()

    def tearDown(self) -> None:
        pass

    def test_add_forward_host(self) -> None:
        """Test case for add_forward_host

        Add Forward Host
        """
        pass

    def test_delete_forward_host(self) -> None:
        """Test case for delete_forward_host

        Delete Forward Host
        """
        pass

    def test_get_forwarding_hosts(self) -> None:
        """Test case for get_forwarding_hosts

        Get Forwarding Hosts
        """
        pass


if __name__ == '__main__':
    unittest.main()
