# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.models.edit_external_identity_provider_settings_request_attr import EditExternalIdentityProviderSettingsRequestAttr

class TestEditExternalIdentityProviderSettingsRequestAttr(unittest.TestCase):
    """EditExternalIdentityProviderSettingsRequestAttr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditExternalIdentityProviderSettingsRequestAttr:
        """Test EditExternalIdentityProviderSettingsRequestAttr
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditExternalIdentityProviderSettingsRequestAttr`
        """
        model = EditExternalIdentityProviderSettingsRequestAttr()
        if include_optional:
            return EditExternalIdentityProviderSettingsRequestAttr(
                authsource = 'ldap',
                server_url = '',
                realm = '',
                client_id = '',
                client_secret = '',
                redirect_url = '',
                redirect_url_extra = [
                    null
                    ],
                version = '',
                default_template = '',
                mappers = [
                    null
                    ],
                templates = [
                    null
                    ],
                ignore_ssl_error = True,
                mailpassword_flow = True,
                periodic_sync = True,
                import_users = True,
                sync_interval = 1.337,
                host = '',
                port = '',
                use_ssl = True,
                use_tls = True,
                basedn = '',
                username_field = 'mail',
                filter = '',
                attribute_field = '',
                binddn = '',
                bindpass = '',
                authorize_url = '',
                token_url = '',
                userinfo_url = '',
                client_scopes = 'openid profile email mailcow_template'
            )
        else:
            return EditExternalIdentityProviderSettingsRequestAttr(
        )
        """

    def testEditExternalIdentityProviderSettingsRequestAttr(self):
        """Test EditExternalIdentityProviderSettingsRequestAttr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
