# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.models.edit_fail2_ban_request import EditFail2BanRequest

class TestEditFail2BanRequest(unittest.TestCase):
    """EditFail2BanRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditFail2BanRequest:
        """Test EditFail2BanRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditFail2BanRequest`
        """
        model = EditFail2BanRequest()
        if include_optional:
            return EditFail2BanRequest(
                attr = mailcow_sdk.models.edit_fail2_ban_request_attr.Edit_Fail2Ban_request_attr(
                    backlist = '', 
                    ban_time = 1.337, 
                    ban_time_increment = True, 
                    max_attempts = 1.337, 
                    max_ban_time = 1.337, 
                    netban_ipv4 = 1.337, 
                    netban_ipv6 = 1.337, 
                    retry_window = 1.337, 
                    whitelist = '', ),
                items = None
            )
        else:
            return EditFail2BanRequest(
        )
        """

    def testEditFail2BanRequest(self):
        """Test EditFail2BanRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
