# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.models.create_sync_job_request import CreateSyncJobRequest

class TestCreateSyncJobRequest(unittest.TestCase):
    """CreateSyncJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSyncJobRequest:
        """Test CreateSyncJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSyncJobRequest`
        """
        model = CreateSyncJobRequest()
        if include_optional:
            return CreateSyncJobRequest(
                parameters = '',
                host1 = '',
                port1 = '',
                user1 = '',
                password = '',
                enc1 = '',
                mins_internal = 1.337,
                subfolder2 = '',
                maxage = 1.337,
                maxbytespersecond = 1.337,
                timeout1 = 1.337,
                timeout2 = 1.337,
                exclude = '',
                custom_params = '',
                delete2duplicates = True,
                delete1 = True,
                delete2 = True,
                automap = True,
                skipcrossduplicates = True,
                subscribeall = True,
                active = True
            )
        else:
            return CreateSyncJobRequest(
        )
        """

    def testCreateSyncJobRequest(self):
        """Test CreateSyncJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
