# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.api.dkim_api import DKIMApi


class TestDKIMApi(unittest.TestCase):
    """DKIMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DKIMApi()

    def tearDown(self) -> None:
        pass

    def test_delete_dkim_key(self) -> None:
        """Test case for delete_dkim_key

        Delete DKIM Key
        """
        pass

    def test_duplicate_dkim_key(self) -> None:
        """Test case for duplicate_dkim_key

        Duplicate DKIM Key
        """
        pass

    def test_generate_dkim_key(self) -> None:
        """Test case for generate_dkim_key

        Generate DKIM Key
        """
        pass

    def test_get_dkim_key(self) -> None:
        """Test case for get_dkim_key

        Get DKIM Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
