# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailcow_sdk.models.create_resources_request import CreateResourcesRequest

class TestCreateResourcesRequest(unittest.TestCase):
    """CreateResourcesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateResourcesRequest:
        """Test CreateResourcesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateResourcesRequest`
        """
        model = CreateResourcesRequest()
        if include_optional:
            return CreateResourcesRequest(
                active = 1.337,
                description = '',
                domain = '',
                kind = 'location',
                multiple_bookings = '-1',
                multiple_bookings_custom = 1.337,
                multiple_bookings_select = '-1'
            )
        else:
            return CreateResourcesRequest(
        )
        """

    def testCreateResourcesRequest(self):
        """Test CreateResourcesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
