# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreateSyncJobRequest(BaseModel):
    """
    CreateSyncJobRequest
    """ # noqa: E501
    parameters: Optional[StrictStr] = Field(default=None, description="your local mailcow mailbox")
    host1: Optional[StrictStr] = Field(default=None, description="the smtp server where mails should be synced from")
    port1: Optional[StrictStr] = Field(default=None, description="the smtp port of the target mail server")
    user1: Optional[StrictStr] = Field(default=None, description="the username of the mailbox")
    password: Optional[StrictStr] = Field(default=None, description="the password of the mailbox")
    enc1: Optional[StrictStr] = Field(default=None, description="the encryption method used to connect to the mailserver")
    mins_internal: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="the interval in which messages should be syned")
    subfolder2: Optional[StrictStr] = Field(default=None, description="sync into subfolder on destination (empty = do not use subfolder)")
    maxage: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="only sync messages up to this age in days")
    maxbytespersecond: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="max speed transfer limit for the sync")
    timeout1: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="timeout for connection to remote host")
    timeout2: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="timeout for connection to local host")
    exclude: Optional[StrictStr] = Field(default=None, description="exclude objects (regex)")
    custom_params: Optional[StrictStr] = Field(default=None, description="custom parameters")
    delete2duplicates: Optional[StrictBool] = Field(default=None, description="delete duplicates on destination (--delete2duplicates)")
    delete1: Optional[StrictBool] = Field(default=None, description="delete from source when completed (--delete1)")
    delete2: Optional[StrictBool] = Field(default=None, description="delete messages on destination that are not on source (--delete2)")
    automap: Optional[StrictBool] = Field(default=None, description="try to automap folders (\"Sent items\", \"Sent\" => \"Sent\" etc.) (--automap)")
    skipcrossduplicates: Optional[StrictBool] = Field(default=None, description="skip duplicate messages across folders (first come, first serve) (--skipcrossduplicates)")
    subscribeall: Optional[StrictBool] = Field(default=None, description="subscribe all folders (--subscribeall)")
    active: Optional[StrictBool] = Field(default=None, description="enables or disables the sync job")
    __properties: ClassVar[List[str]] = ["parameters", "host1", "port1", "user1", "password", "enc1", "mins_internal", "subfolder2", "maxage", "maxbytespersecond", "timeout1", "timeout2", "exclude", "custom_params", "delete2duplicates", "delete1", "delete2", "automap", "skipcrossduplicates", "subscribeall", "active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSyncJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSyncJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parameters": obj.get("parameters"),
            "host1": obj.get("host1"),
            "port1": obj.get("port1"),
            "user1": obj.get("user1"),
            "password": obj.get("password"),
            "enc1": obj.get("enc1"),
            "mins_internal": obj.get("mins_internal"),
            "subfolder2": obj.get("subfolder2"),
            "maxage": obj.get("maxage"),
            "maxbytespersecond": obj.get("maxbytespersecond"),
            "timeout1": obj.get("timeout1"),
            "timeout2": obj.get("timeout2"),
            "exclude": obj.get("exclude"),
            "custom_params": obj.get("custom_params"),
            "delete2duplicates": obj.get("delete2duplicates"),
            "delete1": obj.get("delete1"),
            "delete2": obj.get("delete2"),
            "automap": obj.get("automap"),
            "skipcrossduplicates": obj.get("skipcrossduplicates"),
            "subscribeall": obj.get("subscribeall"),
            "active": obj.get("active")
        })
        return _obj


