# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CreateMailboxRequest(BaseModel):
    """
    CreateMailboxRequest
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, description="is mailbox active or not")
    domain: Optional[StrictStr] = Field(default=None, description="domain name")
    local_part: Optional[StrictStr] = Field(default=None, description="left part of email address")
    name: Optional[StrictStr] = Field(default=None, description="Full name of the mailbox user")
    authsource: Optional[StrictStr] = Field(default='mailcow', description="Specifies the authentication source for the mailbox.")
    password2: Optional[StrictStr] = Field(default=None, description="mailbox password for confirmation")
    password: Optional[StrictStr] = Field(default=None, description="mailbox password when using `mailcow` as the authentication source.")
    quota: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="mailbox quota")
    force_pw_update: Optional[StrictBool] = Field(default=None, description="forces the user to update its password on first login")
    tls_enforce_in: Optional[StrictBool] = Field(default=None, description="force inbound email tls encryption")
    tls_enforce_out: Optional[StrictBool] = Field(default=None, description="force oubound tmail tls encryption")
    __properties: ClassVar[List[str]] = ["active", "domain", "local_part", "name", "authsource", "password2", "password", "quota", "force_pw_update", "tls_enforce_in", "tls_enforce_out"]

    @field_validator('authsource')
    def authsource_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['mailcow', 'ldap', 'keycloak', 'generic-oidc']):
            raise ValueError("must be one of enum values ('mailcow', 'ldap', 'keycloak', 'generic-oidc')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateMailboxRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateMailboxRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "domain": obj.get("domain"),
            "local_part": obj.get("local_part"),
            "name": obj.get("name"),
            "authsource": obj.get("authsource") if obj.get("authsource") is not None else 'mailcow',
            "password2": obj.get("password2"),
            "password": obj.get("password"),
            "quota": obj.get("quota"),
            "force_pw_update": obj.get("force_pw_update"),
            "tls_enforce_in": obj.get("tls_enforce_in"),
            "tls_enforce_out": obj.get("tls_enforce_out")
        })
        return _obj


