# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class UpdateDomainRequestAttr(BaseModel):
    """
    UpdateDomainRequestAttr
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, description="is domain active or not")
    aliases: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="limit count of aliases associated with this domain")
    backupmx: Optional[StrictBool] = Field(default=None, description="relay domain or not")
    defquota: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="predefined mailbox quota in `add mailbox` form")
    description: Optional[StrictStr] = Field(default=None, description="Description of domain")
    gal: Optional[StrictBool] = Field(default=None, description="is domain global address list active or not, it enables shared contacts accross domain in SOGo webmail")
    mailboxes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="limit count of mailboxes associated with this domain")
    maxquota: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="maximum quota per mailbox")
    quota: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="maximum quota for this domain (for all mailboxes in sum)")
    relay_all_recipients: Optional[StrictBool] = Field(default=None, description="if not, them you have to create \"dummy\" mailbox for each address to relay")
    relay_unknown_only: Optional[StrictBool] = Field(default=None, description="Relay non-existing mailboxes only. Existing mailboxes will be delivered locally.")
    relayhost: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="id of relayhost")
    rl_frame: Optional[StrictStr] = None
    rl_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="rate limit value")
    tags: Optional[List[StrictStr]] = Field(default=None, description="tags for this Domain")
    __properties: ClassVar[List[str]] = ["active", "aliases", "backupmx", "defquota", "description", "gal", "mailboxes", "maxquota", "quota", "relay_all_recipients", "relay_unknown_only", "relayhost", "rl_frame", "rl_value", "tags"]

    @field_validator('rl_frame')
    def rl_frame_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['s', 'm', 'h', 'd']):
            raise ValueError("must be one of enum values ('s', 'm', 'h', 'd')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateDomainRequestAttr from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateDomainRequestAttr from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "aliases": obj.get("aliases"),
            "backupmx": obj.get("backupmx"),
            "defquota": obj.get("defquota"),
            "description": obj.get("description"),
            "gal": obj.get("gal"),
            "mailboxes": obj.get("mailboxes"),
            "maxquota": obj.get("maxquota"),
            "quota": obj.get("quota"),
            "relay_all_recipients": obj.get("relay_all_recipients"),
            "relay_unknown_only": obj.get("relay_unknown_only"),
            "relayhost": obj.get("relayhost"),
            "rl_frame": obj.get("rl_frame"),
            "rl_value": obj.get("rl_value"),
            "tags": obj.get("tags")
        })
        return _obj


