# coding: utf-8

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class UpdatePushoverSettingsRequestAttr(BaseModel):
    """
    UpdatePushoverSettingsRequestAttr
    """ # noqa: E501
    active: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Enables pushover 1 disable pushover 0")
    evaluate_x_prio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Send the Push with High priority")
    key: Optional[StrictStr] = Field(default=None, description="Pushover key")
    only_x_prio: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Only send push for prio mails")
    sound: Optional[StrictStr] = Field(default=None, description="Set notification sound")
    senders: Optional[StrictStr] = Field(default=None, description="Only send push for emails from these senders")
    senders_regex: Optional[StrictStr] = Field(default=None, description="Regex to match senders for which a push will be send")
    text: Optional[StrictStr] = Field(default=None, description="Custom push noficiation text")
    title: Optional[StrictStr] = Field(default=None, description="Push title")
    token: Optional[StrictStr] = Field(default=None, description="Pushover token")
    __properties: ClassVar[List[str]] = ["active", "evaluate_x_prio", "key", "only_x_prio", "sound", "senders", "senders_regex", "text", "title", "token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdatePushoverSettingsRequestAttr from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdatePushoverSettingsRequestAttr from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "evaluate_x_prio": obj.get("evaluate_x_prio"),
            "key": obj.get("key"),
            "only_x_prio": obj.get("only_x_prio"),
            "sound": obj.get("sound"),
            "senders": obj.get("senders"),
            "senders_regex": obj.get("senders_regex"),
            "text": obj.get("text"),
            "title": obj.get("title"),
            "token": obj.get("token")
        })
        return _obj


