# coding: utf-8

# flake8: noqa

"""
    mailcow API

    mailcow is complete e-mailing solution with advanced antispam, antivirus, nice UI and API.  In order to use this API you have to create a API key and add your IP address to the whitelist of allowed IPs this can be done by logging into the Mailcow UI using your admin account, then go to Configuration > Access > Edit administrator details > API. There you will find a collapsed API menu.  There are two types of API keys   - The read only key can only be used for all get endpoints   - The read write key can be used for all endpoints

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AddressRewritingApi",
    "AliasesApi",
    "AppPasswordsApi",
    "CrossOriginResourceSharingCORSApi",
    "DKIMApi",
    "DomainAdminApi",
    "DomainAntispamPoliciesApi",
    "DomainsApi",
    "Fail2BanApi",
    "FordwardingHostsApi",
    "IdentityProviderApi",
    "LogsApi",
    "MailboxesApi",
    "OutgoingTLSPolicyMapOverridesApi",
    "QuarantineApi",
    "QueueManagerApi",
    "RatelimitsApi",
    "ResourcesApi",
    "RoutingApi",
    "SingleSignOnApi",
    "StatusApi",
    "SyncJobsApi",
    "OAuthClientsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddForwardHostRequest",
    "CreateAlias200Response",
    "CreateAliasRequest",
    "CreateAppPasswordRequest",
    "CreateBCCMapRequest",
    "CreateDomainAdminUserRequest",
    "CreateDomainPolicyRequest",
    "CreateDomainRequest",
    "CreateMailboxRequest",
    "CreateOAuthClientRequest",
    "CreateRecipientMapRequest",
    "CreateResourcesRequest",
    "CreateSenderDependentTransportsRequest",
    "CreateSyncJobRequest",
    "CreateTLSPolicyMapRequest",
    "CreateTimeLimitedAliasRequest",
    "CreateTransportMapsRequest",
    "DeleteAppPasswordRequest",
    "DeleteBCCMapRequest",
    "DeleteDomainAdminRequest",
    "DeleteDomainPolicyRequest",
    "DeleteDomainRequest",
    "DeleteDomainTagsRequest",
    "DeleteForwardHostRequest",
    "DeleteMailboxRequest",
    "DeleteMailboxTagsRequest",
    "DeleteMailsInQuarantineRequest",
    "DeleteOAuthClientRequest",
    "DeleteQueueRequest",
    "DeleteRecipientMapRequest",
    "DeleteResourcesRequest",
    "DeleteSenderDependentTransportsRequest",
    "DeleteSyncJobRequest",
    "DeleteTLSPolicyMapRequest",
    "DeleteTransportMapsRequest",
    "DuplicateDKIMKeyRequest",
    "EditCrossOriginResourceSharingCORSSettingsRequest",
    "EditCrossOriginResourceSharingCORSSettingsRequestAttr",
    "EditDomainAdminACLRequest",
    "EditDomainAdminACLRequestAttr",
    "EditDomainAdminUserRequest",
    "EditDomainAdminUserRequestAttr",
    "EditDomainRatelimitsRequest",
    "EditExternalIdentityProviderSettingsRequest",
    "EditExternalIdentityProviderSettingsRequestAttr",
    "EditFail2BanRequest",
    "EditFail2BanRequestAttr",
    "EditMailboxRatelimitsRequest",
    "EditMailboxRatelimitsRequestAttr",
    "FlushQueueRequest",
    "GenerateDKIMKeyRequest",
    "InlineObject",
    "IssueDomainAdminSSOTokenRequest",
    "QuarantineNotificationsRequest",
    "QuarantineNotificationsRequestAttr",
    "UpdateAliasRequest",
    "UpdateAliasRequestAttr",
    "UpdateDomainRequest",
    "UpdateDomainRequestAttr",
    "UpdateDomainWideFooterRequest",
    "UpdateDomainWideFooterRequestAttr",
    "UpdateMailboxACLRequest",
    "UpdateMailboxACLRequestAttr",
    "UpdateMailboxCustomAttributesRequest",
    "UpdateMailboxCustomAttributesRequestAttr",
    "UpdateMailboxRequest",
    "UpdateMailboxRequestAttr",
    "UpdatePushoverSettingsRequest",
    "UpdatePushoverSettingsRequestAttr",
    "UpdateSyncJobRequest",
    "UpdateSyncJobRequestAttr",
]

# import apis into sdk package
from mailcow_sdk.api.address_rewriting_api import AddressRewritingApi as AddressRewritingApi
from mailcow_sdk.api.aliases_api import AliasesApi as AliasesApi
from mailcow_sdk.api.app_passwords_api import AppPasswordsApi as AppPasswordsApi
from mailcow_sdk.api.cross_origin_resource_sharing_cors_api import CrossOriginResourceSharingCORSApi as CrossOriginResourceSharingCORSApi
from mailcow_sdk.api.dkim_api import DKIMApi as DKIMApi
from mailcow_sdk.api.domain_admin_api import DomainAdminApi as DomainAdminApi
from mailcow_sdk.api.domain_antispam_policies_api import DomainAntispamPoliciesApi as DomainAntispamPoliciesApi
from mailcow_sdk.api.domains_api import DomainsApi as DomainsApi
from mailcow_sdk.api.fail2_ban_api import Fail2BanApi as Fail2BanApi
from mailcow_sdk.api.fordwarding_hosts_api import FordwardingHostsApi as FordwardingHostsApi
from mailcow_sdk.api.identity_provider_api import IdentityProviderApi as IdentityProviderApi
from mailcow_sdk.api.logs_api import LogsApi as LogsApi
from mailcow_sdk.api.mailboxes_api import MailboxesApi as MailboxesApi
from mailcow_sdk.api.outgoing_tls_policy_map_overrides_api import OutgoingTLSPolicyMapOverridesApi as OutgoingTLSPolicyMapOverridesApi
from mailcow_sdk.api.quarantine_api import QuarantineApi as QuarantineApi
from mailcow_sdk.api.queue_manager_api import QueueManagerApi as QueueManagerApi
from mailcow_sdk.api.ratelimits_api import RatelimitsApi as RatelimitsApi
from mailcow_sdk.api.resources_api import ResourcesApi as ResourcesApi
from mailcow_sdk.api.routing_api import RoutingApi as RoutingApi
from mailcow_sdk.api.single_sign_on_api import SingleSignOnApi as SingleSignOnApi
from mailcow_sdk.api.status_api import StatusApi as StatusApi
from mailcow_sdk.api.sync_jobs_api import SyncJobsApi as SyncJobsApi
from mailcow_sdk.api.o_auth_clients_api import OAuthClientsApi as OAuthClientsApi

# import ApiClient
from mailcow_sdk.api_response import ApiResponse as ApiResponse
from mailcow_sdk.api_client import ApiClient as ApiClient
from mailcow_sdk.configuration import Configuration as Configuration
from mailcow_sdk.exceptions import OpenApiException as OpenApiException
from mailcow_sdk.exceptions import ApiTypeError as ApiTypeError
from mailcow_sdk.exceptions import ApiValueError as ApiValueError
from mailcow_sdk.exceptions import ApiKeyError as ApiKeyError
from mailcow_sdk.exceptions import ApiAttributeError as ApiAttributeError
from mailcow_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from mailcow_sdk.models.add_forward_host_request import AddForwardHostRequest as AddForwardHostRequest
from mailcow_sdk.models.create_alias200_response import CreateAlias200Response as CreateAlias200Response
from mailcow_sdk.models.create_alias_request import CreateAliasRequest as CreateAliasRequest
from mailcow_sdk.models.create_app_password_request import CreateAppPasswordRequest as CreateAppPasswordRequest
from mailcow_sdk.models.create_bcc_map_request import CreateBCCMapRequest as CreateBCCMapRequest
from mailcow_sdk.models.create_domain_admin_user_request import CreateDomainAdminUserRequest as CreateDomainAdminUserRequest
from mailcow_sdk.models.create_domain_policy_request import CreateDomainPolicyRequest as CreateDomainPolicyRequest
from mailcow_sdk.models.create_domain_request import CreateDomainRequest as CreateDomainRequest
from mailcow_sdk.models.create_mailbox_request import CreateMailboxRequest as CreateMailboxRequest
from mailcow_sdk.models.create_o_auth_client_request import CreateOAuthClientRequest as CreateOAuthClientRequest
from mailcow_sdk.models.create_recipient_map_request import CreateRecipientMapRequest as CreateRecipientMapRequest
from mailcow_sdk.models.create_resources_request import CreateResourcesRequest as CreateResourcesRequest
from mailcow_sdk.models.create_sender_dependent_transports_request import CreateSenderDependentTransportsRequest as CreateSenderDependentTransportsRequest
from mailcow_sdk.models.create_sync_job_request import CreateSyncJobRequest as CreateSyncJobRequest
from mailcow_sdk.models.create_tls_policy_map_request import CreateTLSPolicyMapRequest as CreateTLSPolicyMapRequest
from mailcow_sdk.models.create_time_limited_alias_request import CreateTimeLimitedAliasRequest as CreateTimeLimitedAliasRequest
from mailcow_sdk.models.create_transport_maps_request import CreateTransportMapsRequest as CreateTransportMapsRequest
from mailcow_sdk.models.delete_app_password_request import DeleteAppPasswordRequest as DeleteAppPasswordRequest
from mailcow_sdk.models.delete_bcc_map_request import DeleteBCCMapRequest as DeleteBCCMapRequest
from mailcow_sdk.models.delete_domain_admin_request import DeleteDomainAdminRequest as DeleteDomainAdminRequest
from mailcow_sdk.models.delete_domain_policy_request import DeleteDomainPolicyRequest as DeleteDomainPolicyRequest
from mailcow_sdk.models.delete_domain_request import DeleteDomainRequest as DeleteDomainRequest
from mailcow_sdk.models.delete_domain_tags_request import DeleteDomainTagsRequest as DeleteDomainTagsRequest
from mailcow_sdk.models.delete_forward_host_request import DeleteForwardHostRequest as DeleteForwardHostRequest
from mailcow_sdk.models.delete_mailbox_request import DeleteMailboxRequest as DeleteMailboxRequest
from mailcow_sdk.models.delete_mailbox_tags_request import DeleteMailboxTagsRequest as DeleteMailboxTagsRequest
from mailcow_sdk.models.delete_mails_in_quarantine_request import DeleteMailsInQuarantineRequest as DeleteMailsInQuarantineRequest
from mailcow_sdk.models.delete_o_auth_client_request import DeleteOAuthClientRequest as DeleteOAuthClientRequest
from mailcow_sdk.models.delete_queue_request import DeleteQueueRequest as DeleteQueueRequest
from mailcow_sdk.models.delete_recipient_map_request import DeleteRecipientMapRequest as DeleteRecipientMapRequest
from mailcow_sdk.models.delete_resources_request import DeleteResourcesRequest as DeleteResourcesRequest
from mailcow_sdk.models.delete_sender_dependent_transports_request import DeleteSenderDependentTransportsRequest as DeleteSenderDependentTransportsRequest
from mailcow_sdk.models.delete_sync_job_request import DeleteSyncJobRequest as DeleteSyncJobRequest
from mailcow_sdk.models.delete_tls_policy_map_request import DeleteTLSPolicyMapRequest as DeleteTLSPolicyMapRequest
from mailcow_sdk.models.delete_transport_maps_request import DeleteTransportMapsRequest as DeleteTransportMapsRequest
from mailcow_sdk.models.duplicate_dkim_key_request import DuplicateDKIMKeyRequest as DuplicateDKIMKeyRequest
from mailcow_sdk.models.edit_cross_origin_resource_sharing_cors_settings_request import EditCrossOriginResourceSharingCORSSettingsRequest as EditCrossOriginResourceSharingCORSSettingsRequest
from mailcow_sdk.models.edit_cross_origin_resource_sharing_cors_settings_request_attr import EditCrossOriginResourceSharingCORSSettingsRequestAttr as EditCrossOriginResourceSharingCORSSettingsRequestAttr
from mailcow_sdk.models.edit_domain_admin_acl_request import EditDomainAdminACLRequest as EditDomainAdminACLRequest
from mailcow_sdk.models.edit_domain_admin_acl_request_attr import EditDomainAdminACLRequestAttr as EditDomainAdminACLRequestAttr
from mailcow_sdk.models.edit_domain_admin_user_request import EditDomainAdminUserRequest as EditDomainAdminUserRequest
from mailcow_sdk.models.edit_domain_admin_user_request_attr import EditDomainAdminUserRequestAttr as EditDomainAdminUserRequestAttr
from mailcow_sdk.models.edit_domain_ratelimits_request import EditDomainRatelimitsRequest as EditDomainRatelimitsRequest
from mailcow_sdk.models.edit_external_identity_provider_settings_request import EditExternalIdentityProviderSettingsRequest as EditExternalIdentityProviderSettingsRequest
from mailcow_sdk.models.edit_external_identity_provider_settings_request_attr import EditExternalIdentityProviderSettingsRequestAttr as EditExternalIdentityProviderSettingsRequestAttr
from mailcow_sdk.models.edit_fail2_ban_request import EditFail2BanRequest as EditFail2BanRequest
from mailcow_sdk.models.edit_fail2_ban_request_attr import EditFail2BanRequestAttr as EditFail2BanRequestAttr
from mailcow_sdk.models.edit_mailbox_ratelimits_request import EditMailboxRatelimitsRequest as EditMailboxRatelimitsRequest
from mailcow_sdk.models.edit_mailbox_ratelimits_request_attr import EditMailboxRatelimitsRequestAttr as EditMailboxRatelimitsRequestAttr
from mailcow_sdk.models.flush_queue_request import FlushQueueRequest as FlushQueueRequest
from mailcow_sdk.models.generate_dkim_key_request import GenerateDKIMKeyRequest as GenerateDKIMKeyRequest
from mailcow_sdk.models.inline_object import InlineObject as InlineObject
from mailcow_sdk.models.issue_domain_admin_sso_token_request import IssueDomainAdminSSOTokenRequest as IssueDomainAdminSSOTokenRequest
from mailcow_sdk.models.quarantine_notifications_request import QuarantineNotificationsRequest as QuarantineNotificationsRequest
from mailcow_sdk.models.quarantine_notifications_request_attr import QuarantineNotificationsRequestAttr as QuarantineNotificationsRequestAttr
from mailcow_sdk.models.update_alias_request import UpdateAliasRequest as UpdateAliasRequest
from mailcow_sdk.models.update_alias_request_attr import UpdateAliasRequestAttr as UpdateAliasRequestAttr
from mailcow_sdk.models.update_domain_request import UpdateDomainRequest as UpdateDomainRequest
from mailcow_sdk.models.update_domain_request_attr import UpdateDomainRequestAttr as UpdateDomainRequestAttr
from mailcow_sdk.models.update_domain_wide_footer_request import UpdateDomainWideFooterRequest as UpdateDomainWideFooterRequest
from mailcow_sdk.models.update_domain_wide_footer_request_attr import UpdateDomainWideFooterRequestAttr as UpdateDomainWideFooterRequestAttr
from mailcow_sdk.models.update_mailbox_acl_request import UpdateMailboxACLRequest as UpdateMailboxACLRequest
from mailcow_sdk.models.update_mailbox_acl_request_attr import UpdateMailboxACLRequestAttr as UpdateMailboxACLRequestAttr
from mailcow_sdk.models.update_mailbox_custom_attributes_request import UpdateMailboxCustomAttributesRequest as UpdateMailboxCustomAttributesRequest
from mailcow_sdk.models.update_mailbox_custom_attributes_request_attr import UpdateMailboxCustomAttributesRequestAttr as UpdateMailboxCustomAttributesRequestAttr
from mailcow_sdk.models.update_mailbox_request import UpdateMailboxRequest as UpdateMailboxRequest
from mailcow_sdk.models.update_mailbox_request_attr import UpdateMailboxRequestAttr as UpdateMailboxRequestAttr
from mailcow_sdk.models.update_pushover_settings_request import UpdatePushoverSettingsRequest as UpdatePushoverSettingsRequest
from mailcow_sdk.models.update_pushover_settings_request_attr import UpdatePushoverSettingsRequestAttr as UpdatePushoverSettingsRequestAttr
from mailcow_sdk.models.update_sync_job_request import UpdateSyncJobRequest as UpdateSyncJobRequest
from mailcow_sdk.models.update_sync_job_request_attr import UpdateSyncJobRequestAttr as UpdateSyncJobRequestAttr

